### ISSUE TITLE
T1 Amphibious Fabricator Bot

### ISSUE THREAD

**Issue by Stuart1998** [Planetary-Obliteration/PlanetaryObliteration#29]
Create a new amphibious fabricator model.

**Comment by nicb1** [comment]
What unit class is this exactly? Does it go underwater? Does it hover? is it bot or tank based?.
Sorry just need to know these things before I give the model a shot.

**Comment by Stuart1998** [comment]
Clarified title

**Comment by Stuart1998** [comment]
Not doing this for the sake of icon atlas conservation.
