### ISSUE TITLE
Hyperion attack causes clients to crash

### ISSUE THREAD

**Issue by Mogball** [Planetary-Obliteration/PlanetaryObliteration#55]
Building the unit and moving it around is fine, but when the unit attacks, all clients in the game will crash.

However, it seems that clients with the client-side mod "More pew pew" installed will not crash when the Hyperion attacks.

**Comment by Stuart1998** [comment]
Interesting, I'll take a look.

**Comment by Stuart1998** [comment]
Fixed in 16.1.2
